<?php
	// require 'facebook.php';

	// $facebook = new Facebook(array(

	// 	'appId' => '1493558364210301',
	// 	'secret' => 'af6adb5ac7baf8ef7f3198f1df8565e4'

	// ));

	// if($facebook ->getUser() == 0){
	// 	$login = $facebook->getLoginUrl();
	// 	echo "<a href = '$login'> Login with Facebook </a>";
	// }
	// else{
	// 	echo "You are now logged in using facebook.";
	// }

?>

<html lang=en">
	<head>
		<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
		<link href="http://s3.amazonaws.com/codecademy-content/courses/ltp/css/bootstrap.css" rel="stylesheet">
		<link href="http://mynameismatthieu.com/WOW/css/libs/animate.css" rel="stylesheet">
		<script type="text/javascript" src="http://code.jquery.com/jquery-1.8.0.min.js"></script>

		<script src="http://scrollrevealjs.org/js/scrollReveal.min.js"></script>
		<script>
		    window.scrollReveal = new scrollReveal();
		</script>

		<script type="text/javascript" src="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.1.0/js/bootstrap.min.js"></script>
		<script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
		<script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
		<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.1/jquery-ui.min.js"></script>
		<script type="text/javascript" src="http://creativecouple.github.io/jquery-timing/documentation.js?v=20130928-164118"></script>
		<script type="text/javascript" src="http://creativecouple.github.io/jquery-timing/jquery-timing.min.js?v=20130928-164118"></script>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<link rel="shortcut icon" href="img/icon.png">
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>Jona Ranola</title>
	</head>

	<body>
 <body>

    <div class="headContent">
      	<div class="container">
      		<div class="row">
				<div class="col-md-6">
					<div class="animation" style="background-image: url('img/browser.png');">
						<br />
						<br />
						<br />
						<p><span class="topText">like. starred. dislike</span></p>
						<br />
						<img src="img/temp1.png" class="wow fadeInUp" data-wow-delay="0.5s">
						<img src="img/temp2.png" class="wow bounceIn" data-wow-delay="1.5s">
						<img src="img/temp3.png" class="wow fadeInDown" data-wow-delay="1s">
					</div>
				</div>
				<div class="col-md-6">
					<br />
					<br />
					
						
						<div class="name">
							<section class="wow slideInDown" data-wow-delay="1.5s">
								<h1>UPushed!</h1>
							</section>

							<span class="topText">
								Push it hard.
							</span>
						</div>
					<br />
						<div class="nameButton">
							<a class="boxB">
								<center>Log In</center></a></center>
								<br />
								<br />
							<a class="boxB">
								<center>Sign Up</center>
							</a>
						</div>
				</div>
			</div>
      	</div>
      </div>
	</div> 


    <div class="headHidden">
      	<div class="container">
      		<div class="row">
				<div class="col-md-12">
						<div class="name">
							<section class="wow slideInDown" data-wow-delay="1.5s">
								<h1>UPushed!</h1>
							</section>

							<span class="topText">
								Push it hard.
							</span>
						</div>
					<br />
						<div class="nameButton">
							<a class="boxB">
								<center>Log In</center></a></center>
								<br />
								<br />
							<a class="boxB">
								<center>Sign Up</center>
							</a>
						</div>
						<div class="imgHidden">
							<img src="img/temp1.png" class="wow fadeInUp" data-wow-delay="0.5s">
							<img src="img/temp2.png" class="wow bounceIn" data-wow-delay="1.5s">
							<img src="img/temp3.png" class="wow fadeInDown" data-wow-delay="1s">
						</div>
						<br />
						<br />
				</div>
			</div>
      	</div>
      </div>
	</div> 
    <div class="nav">
		<div class="container">
        	<div class="container">
			    <ul class="pull-left" id="navshow">
			        <li><a href="#"><font style="font-family: lobster; text-transform: lowercase; font-size: 18px;">upushed</font></a></li>
			        <li><a href="#">Browse</a></li>
			    </ul>
			    <ul class="pull-right" id="navhid">
			        <li><a href="#">Log In</a></li>
			        <li><a href="#">Sign Up</a></li>
			        <li><a href="#">About</a></li>
			    </ul>
			</div>
	  	</div>
	</div>
  

  <div class="blogFoot">
  	<div class="container">
  			
		<div class="row">
  <br />
	  	  <div class="col-md-3">
	  	  	<div class="gallery">
	  	  		<center>
	  	  			<img src="img/nav.png">
					<h3>Travel</h3>
					<p>From apartments and rooms to treehouses and boats: stay in unique spaces in 192 countries.</p>
					<p><a href="#" class="boxA">See more</a></p>
				</center>
			</div>
		  </div>
		  <div class="col-md-3">
	  	  	<div class="gallery">
		  	  	<center>
		  	  		<img src="img/nav.png">
					<h3>Travel</h3>
					<p>From apartments and rooms to treehouses and boats: stay in unique spaces in 192 countries.</p>
					<p><a href="#" class="boxA">See more</a></p>
				</center>
			</div>
	      </div>
		  <div class="col-md-3">
	  	  	<div class="gallery">
		  	  	<center>
		  	  		<img src="img/nav.png">
					<h3>Travel</h3>
					<p>From apartments and rooms to treehouses and boats: stay in unique spaces in 192 countries.</p>
					<p><a href="#" class="boxA">See more</a></p>
				</center>
			</div>
		</div>
		  <div class="col-md-3">
	  	  	<div class="gallery">
		  	  	<center>
		  	  		<img src="img/nav.png">
					<h3>Travel</h3>
					<p>From apartments and rooms to treehouses and boats: stay in unique spaces in 192 countries.</p>
					<p><a href="#" class="boxA">See more</a></p>
				</center>
			</div>
		  </div>
		  </div>
		  </div>
 <div class="container">
		<div class="row">
  <br />
	  	  <div class="col-md-3">
	  	  	<div class="gallery">
	  	  		<center>
	  	  			<img src="img/nav.png">
					<h3>Travel</h3>
					<p>From apartments and rooms to treehouses and boats: stay in unique spaces in 192 countries.</p>
					<p><a href="#" class="boxA">See more</a></p>
				</center>
			</div>
		  </div>
		  <div class="col-md-3">
	  	  	<div class="gallery">
		  	  	<center>
		  	  		<img src="img/nav.png">
					<h3>Travel</h3>
					<p>From apartments and rooms to treehouses and boats: stay in unique spaces in 192 countries.</p>
					<p><a href="#" class="boxA">See more</a></p>
				</center>
			</div>
	      </div>
		  <div class="col-md-3">
	  	  	<div class="gallery">
		  	  	<center>
		  	  		<img src="img/nav.png">
					<h3>Travel</h3>
					<p>From apartments and rooms to treehouses and boats: stay in unique spaces in 192 countries.</p>
					<p><a href="#" class="boxA">See more</a></p>
				</center>
			</div>
		</div>
		  <div class="col-md-3">
	  	  	<div class="gallery">
		  	  	<center>
		  	  		<img src="img/nav.png">
					<h3>Travel</h3>
					<p>From apartments and rooms to treehouses and boats: stay in unique spaces in 192 countries.</p>
					<p><a href="#" class="boxA">See more</a></p>
				</center>
			</div>
		  </div>

	    </div>
  	</div>

  	<br />
  			<p><center><span class="topText"><a href="#" class="boxC">Browse More</span></a></p></center></p>
  	<br />
  </div>

    <div class="resume">
    	<div class="container">
    		<div class="row">
		  		<div class="col-md-9">
		  			<div class="resumeOn">

						<h3><font style="font-family: lobster; text-transform: lowercase; font-size: 50px; color: #fff;">UPushed!</font></h3>
						<p>Copyright &copy; 2014</p>
						<br />
						<p><b>Contact Us</b></p>
						<p>info@upushed.com</p>
						<p>02 - 239 2243</p>
						<div class="row small center wow fadeInDown top__element" data-wow-delay="0.5s">
							<a href="#"><img src="img/9.png" class="icons" title="Facebook" class="tooltip"></a>
							<a href="#"><img src="img/10.png" class="icons" title="Twitter" class="tooltip"></a>
							<a href="#"><img src="img/11.png" class="icons" title="Google Plus" class="tooltip"></a>
							<a href="#"><img src="img/12.png" class="icons" title="Dribbble" class="tooltip"></a>
							<a href="#"><img src="img/13.png" class="icons" title="Behance" class="tooltip"></a>
						</div>

						</div>
					</div>

		  		<div class="col-md-3">
		  			<br />
					<section class="wow fadeInUp" data-wow-delay="0.5s"><img src="img/temp1.png" style="width: 150px;"></section>
					<br />

				</div>
				<div class="col-md-1"> </div>
    		</div>
	  </div>
    </div>
  </div> 



	</body>
		<script src="http://mynameismatthieu.com/WOW/dist/wow.min.js"></script>
		<script>
			new WOW().init();
		</script>
</html>